#!/usr/bin/env bash
# configure my domain zone that the subdomain points
# to my load-balancer IP.

if [ "$#" = 1 ]
then
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomains[@]}"
	do
		type=$(dig $subdomain.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
		dest=$(dig $subdomain.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
		echo "The subdomain $subdomain is a $type record and points to $dest"
	done
elif [ "$#" = 2 ]
then
	type=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
	dest=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
	echo "The subdomain $2 is a $type record and points to $dest"
fi
