#!/usr/bin/env bash
#install nginx web server

# update
apt-get update -y
# install nginx
apt-get install -y nginx
# allow to listen at :80
ufw allow 'Nginx HTTP'

echo "server {
	listen 80;
	listen [::]:80;

	root /var/www/alx_school;
	index index.htm index.html;
	location / {
	}
}" > /etc/nginx/nginx.conf

#file to server

mkdir -p /var/www/alx_school
echo "Hello World!" > /var/www/alx_school/index.html

#restart nginx
service nginx restart
