#!/usr/bin/env bash
# install nginx web server

sudo apt-get -y update

sudo apt-get -y install nginx

echo "Hello World!" | sudo tee wq
/var/www/html/index.nginx-debian.html

sudo service nginx restart
