#!/usr/bin/env bash
# configure your nginx server so that
# /redirect_me is redirecting to another page.

# update and install nginx
apt-get update
apt-get install -y nginx

# setup a html page for it
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello World!" > etc/nginx/html/index.html

echo "server {
	listen 80;
	listen [::]:80;
	root /etc/nginx/html;
	index index.html;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUIwu4;
	}
}" >> /etc/nginx/sites-available/default

# restart the server
service nginx restart
