#!/usr/bin/env bash
# while looping from 1 to 10, display:
# "bad luck" for 4th iter, 
# "good luck" for the 8th iter
# "Best School" for other iter

i=0

while (( i<10 ))
do
	if [ $i -eq 3 ]
	then
		echo "bad luck"
	elif [ $i -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
