#!/usr/bin/env bash
# Configure a server with the below requirements:
# * localhost - 127.0.0.2
# * facebook - 8.8.8.8

cp /etc/hosts  new_host
sed -i s/^127.*/"127.0.0.2 localhost"/ new_host
echo "8.8.8.8 facebook.com" >> new_host
cp new_host /etc/hosts
